services:
  db:
      image: postgres:16-alpine
      environment:
        POSTGRES_USER:  task_api
        POSTGRES_PASSWORD: task_api
        POSTGRES_DB: task_api
      ports:
        - "5432:5432"
      volumes:
        - task_api_pgdata:/var/lib/postgresql/data

volumes:
  task_api_pgdata:
